model_selection:
  model:
    XGBClassifier:
      search_param_grid:
        n_estimators: [100, 200, 300]
        max_depth: [3, 5, 7]
        learning_rate: [0.01, 0.1, 0.2]
        min_child_weight: [1, 3, 5]
    
    GradientBoostingClassifier:
      search_param_grid:
        n_estimators: [100, 200, 300]
        max_depth: [3, 5, 7]
        learning_rate: [0.01, 0.1, 0.2]
        min_samples_split: [2, 5, 10]
    
    SVC:
      search_param_grid:
        C: [0.1, 1, 10]
        kernel: ['linear', 'rbf', 'poly']
        gamma: ['scale', 'auto', 0.001, 0.01]
    
    RandomForestClassifier:
      search_param_grid:
        n_estimators: [100, 200, 300]
        max_depth: [3, 5, 7, None]
        min_samples_split: [2, 5, 10]
        min_samples_leaf: [1, 2, 4]

